flowchart TD
    %% put eggs in counter
    A(OpenSingleDoor; param: fridge)
    A --> A1{Check eggs ≥ 2?}:::fallback
    A1-->|No| D[NotifyUser]
    D -->|Fail| D1[Abort]
    A1 -->|Yes| A2[Continue]
    A2 --> |no_tries=0|A3[PickPlaceCabinetToCounter; param: egg_1]
    A3-->|FAILED| A4[no_tries>10]
    A4 --> |No| A5[RETRY]
    A5 --> |no_tries++| A3[PickPlaceCabinetToCounter; param: egg_1]
    A3-->|SUCCESS| A6[Continue]
    A6 --> |no_tries=0| A7[PickPlaceCabinetToCounter; param: egg_2]
    A4-->|Yes|D[NotifyUser]
    A7-->  |FAILED| A8[no_tries>10]
    A8 --> |No| A9[RETRY]
    A8 --> |Yes| D[NotifyUser]
    A9 --> |no_tries++| A7[PickPlaceCabinetToCounter; param: egg_2]
    A7 --> |SUCCESS| A10[CloseSingleDoor; param: fridge]
    
    %% pick up the pot from cabinet, put it in the counter, fill it up at sink, and place it on the stove 
    A10 --> B[Prepare Pot]
    B --> B1[OpenDoubleDoor; param: cabinet]
    B1 --> B1_5[Continue]
    B1_5 --> |no_tries=0| B2[PickPlaceCabinetToCounter; param: pot]
    B2 --> |FAILED| B2_1[no_tries>10]
    B2_1 --> |Yes| D2[NotifyUser]
    D2 --> |Fail| D3[Abort]
    B2_1 --> |No| B2_2[Retry]
    B2_2 --> |no_tries++| B2[PickPlaceCabinetToCounter; param: pot]
    B2 --> |SUCCESS| B2_5[Continue]
    B2_5 --> |no_tries=0| B3[PickPlaceCounterToSink; param: pot]
    B3 --> |FAILED| B3_1[no_tries>10]
    B3_1 --> |Yes| D2[NotifyUser]
    B3_1 --> |No| B3_2[Retry]
    B3_2 --> |no_tries++| B3[PickPlaceCounterToSink; param: pot] 
    B3 --> |SUCCESS| B4[TurnOnSinkFaucet; param: sink]
    B4 --> B5[TurnSinkSpout; param: side=right]
    B5 --> B6[Wait; param: seconds = 5]
    B6 --> B7[TurnOffSinkFaucet; param: sink]
    B7 -->  B7_5[Continue]
    B7_5 --> |no_tries=0| B8[PickPlaceSinkToCounter; param: pot]
    B8 --> |FAILED| B8_1[no_tries>10]
    B8_1 --> |Yes| D2[NotifyUser]
    B8_1 --> |No| B8_2[Retry]
    B8_2 --> |no_tries++| B8[PickPlaceSinkToCounter; param: pot] 
    B8 --> |SUCCESS| B8_5[Continue]
    B8_5 --> |no_tries=0| B9[PickPlaceCounterToStove; param: pot]
    B9 --> |FAILED| B9_1[no_tries>10]
    B9_1 --> |Yes| D2[NotifyUser]
    B9_1 --> |No| B9_2[Retry]
    B9_2 --> |no_tries++| B9[PickPlaceCounterToStove; param: pot]
    B9 --> B10[TurnOnStove \n Timeout 30s]
    
    %% place eggs on stove
    B10 --> |Yes| C[Add eggs]
    C -->  C_5[Continue]
    C_5 --> |no_tries=0| C1[PickPlaceCounterToStove; param: egg_1]
    C1 --> |FAILED| C1_1[no_tries>10]
    C1_1 --> |Yes| D4[NotifyUser]
    D4 --> |Fail| D5[Abort]
    C1_1 --> |No| C1_2[Retry]
    C1_2 --> |no_tries++| C1[PickPlaceCounterToStove; param: egg_2]
    C1 --> |SUCCESS| C1_5[Continue]
    C1_5 --> |no_tries=0| C2[PickPlaceCounterToStove; param: egg_2]
    C2 --> |FAILED| C2_1[no_tries>10]
    C2_1 --> |Yes| D4[NotifyUser]
    C2_1 --> |No| C2_2[Retry]
    C2_2 --> |no_tries++| C2[PickPlaceCounterToStove; param: egg_2]
    
    %% boil the eggs for 8 minutes
    C2 --> E[Boil]
    E --> E1[SetTimer; param: seconds=480]
    E1 --> E2[WaitUntil; param: timer_done]
    E2 --> |Yes| E3[TurnOffStove]

    %% fill up the bowl with water
    E3 --> F[Prep Bowl]
    F --> F1[OpenDoubleDoor; param: cabinet]
    F1 --> |SUCCESS| F1_5[Continue]
    F1_5 --> |no_tries=0| F2[PickPlaceCabinetToCounter; param: bowl]
    F2 --> |FAILED| F2_1[no_tries>10]
    F2_1 --> |Yes| D6[NotifyUser]
    D6 --> |Fail| D7[Abort]
    F2_1 --> |No| F2_2[Retry]
    F2_2 --> |no_tries++| F2[PickPlaceCabinetToCounter; param: bowl]
    F2 --> |SUCCESS| F3[CloseDoubleDoor; param: cabinet]
    F3 --> F3_5[Continue]
    F3_5 --> F4[PickPlaceCounterToSink; param: bowl]
    F4 --> |FAILED| F4_1[no_tries>10]
    F4_1 --> |Yes| D6[NotifyUser]
    F4_1 --> |No| F4_2[Retry]
    F4_2 --> |no_tries++| F4[PickPlaceCounterToSink; param: bowl]
    F4 --> |SUCCESS| F5[TurnOnSinkFaucet; param: sink]
    F5 --> F6[TurnSinkSpout; param: side=right]
    F6 --> F7[Wait; param: seconds = 5]
    F7 --> F8[TurnOffSinkFaucet; param: sink]
    F8 --> F8_5[Continue]
    F8_5 --> |no_tries=0| F9[PickPlaceSinkToCounter; param: bowl]
    F9 --> |FAILED| F9_1[no_tries>10]
    F9_1 --> |Yes| D6[NotifyUser]
    F9_1 --> |No| F9_2[Retry]
    F9_2 --> |no_tries++| F9[PickPlaceSinkToCounter; param: bowl]
    
    %% place eggs to bowl
    F9--> |SUCCESS| G[Transfer eggs & Cool]
    G --> G_5[Continue]
    G_5 --> |no_tries=0| G1[PickPlaceStoveToCounter; param: egg_1]
    G1 --> |FAILED| G1_1[no_tries>10]
    G1_1 --> |Yes| D8[NotifyUser]
    D8 --> |Fail| D9[Abort]
    G1_1 --> |No| G1_2[Retry]
    G1_2 --> |no_tries++| G1[PickPlaceCabinetToCounter; param: bowl]
    G1 --> |SUCCESS| G2[PlaceObject; param: src=egg_1, dst=bowl]
    G2 --> G2_5[Continue]
    G2_5 --> |no_tries=0| G3[PickPlaceStoveToCounter; param: egg_2]
    G3 --> |FAILED| G3_1[no_tries>10]
    G3_1 --> |Yes| D8[NotifyUser]
    G3_1 --> |No| G3_2[Retry]
    G3_2 --> |no_tries++| G3[PickPlaceCabinetToCounter; param: bowl]
    G3 --> |SUCCESS| G4[PlaceObject; param: src=egg_2, dst=bowl]
    G4 --> G5[SetTimer; param: seconds=480]
    G5 --> G6[WaitUntil; param: timer_done]

